name: Build Documentation
on:
#   push:
#     branches:
#       - master
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install sphinx sphinx-rtd-theme myst-parser

    - name: Build documentation
      run: |
        cd docs
        make clean
        make html

    - name: Add .nojekyll file
      run: |
        touch docs/build/html/.nojekyll  # Create an empty .nojekyll file in the build directory
  
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/build/html
        branch: gh-pages
        clean: true
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
