name: Build and Upload Package
on:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - 'moduflow/**'
  pull_request:
    branches:
      - master
    types: [closed]
    paths:
      - 'moduflow/**'

jobs:
  build_and_upload:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11.11', '3.12.9', '3.13.2']
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests

    - name: Run tests
      run: pytest

    - name: Build and upload package
      if: matrix.python-version == '3.11.11'
      run: |
        chmod +x build.sh
        ./build.sh
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
